apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ei5x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ei5x
    app.kubernetes.io/part-of: ci1t-830-0092-app
  name: devfile-sample-ei5x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ei5x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ei5x
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0092-tenant/ci1t-830-0092-app/devfile-sample-ei5x@sha256:1977281121466c82d8a96251de81b3c816891da23c029da2b7b85ba8aeae3a99
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
